/**
 * Lightweight, honest export helpers (no document libraries):
 * - CSV: a real comma-separated file (UTF-8 with BOM so Excel reads Arabic/accents).
 * - Print: an HTML document printed through the browser dialog, where "Save as PDF"
 *   produces the PDF. We never label HTML or text as a PDF/XLSX file.
 * - HTML: a self-contained .html document (used for bills and the "Word (HTML)" export).
 */

export type ExportRow = Record<string, string | number>;

function escapeHtml(value: unknown) {
  return String(value).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}

function csvCell(value: unknown) {
  let text = String(value ?? "");
  // Keep spreadsheet apps from evaluating cell text as formulas.
  if (/^[=+\-@]/.test(text)) text = `'${text}`;
  return `"${text.replace(/"/g, '""')}"`;
}

export function toCsv(rows: ExportRow[]) {
  const headers = Object.keys(rows[0] ?? {});
  return [headers, ...rows.map((r) => headers.map((h) => r[h]))].map((line) => line.map(csvCell).join(",")).join("\r\n");
}

export function downloadFile(fileName: string, mime: string, content: string) {
  const url = URL.createObjectURL(new Blob([content], { type: mime }));
  const a = document.createElement("a");
  a.href = url;
  a.download = fileName;
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

export function downloadCsv(fileName: string, rows: ExportRow[]) {
  downloadFile(`${fileName}.csv`, "text/csv;charset=utf-8", `﻿${toCsv(rows)}`);
}

export function htmlTable(rows: ExportRow[]) {
  const headers = Object.keys(rows[0] ?? {});
  if (headers.length === 0) return "<p>No rows.</p>";
  return `<table><thead><tr>${headers.map((h) => `<th>${escapeHtml(h)}</th>`).join("")}</tr></thead><tbody>${rows
    .map((r) => `<tr>${headers.map((h) => `<td>${escapeHtml(r[h])}</td>`).join("")}</tr>`)
    .join("")}</tbody></table>`;
}

const DOCUMENT_CSS = `
  body { font-family: Arial, Helvetica, sans-serif; color: #292d32; margin: 32px; }
  h1 { font-size: 20px; margin: 0 0 4px; color: #214097; }
  .meta { font-size: 12px; color: #75838a; margin: 0 0 20px; }
  table { border-collapse: collapse; width: 100%; font-size: 12px; }
  th, td { border: 1px solid #d6d6d6; padding: 6px 8px; text-align: left; }
  th { background: #fcfcfc; }
  .totals td { font-weight: bold; }
  .note { margin-top: 24px; font-size: 11px; color: #75838a; }
`;

/** Standalone HTML document with the Ncare heading, used for print and HTML downloads. */
export function htmlDocument(title: string, body: string, meta?: string) {
  return `<!doctype html><html><head><meta charset="utf-8"><title>${escapeHtml(title)}</title><style>${DOCUMENT_CSS}</style></head><body><h1>${escapeHtml(
    title,
  )}</h1>${meta ? `<p class="meta">${escapeHtml(meta)}</p>` : ""}${body}<p class="note">Generated by the Ncare dashboard demo from mock data.</p></body></html>`;
}

/**
 * Opens the browser print dialog for an HTML document (via a hidden iframe, so no
 * pop-up permission is needed). Users pick "Save as PDF" there to get a PDF.
 */
export function printHtml(html: string) {
  const frame = document.createElement("iframe");
  frame.setAttribute("aria-hidden", "true");
  frame.style.cssText = "position:fixed;right:0;bottom:0;width:0;height:0;border:0;";
  document.body.appendChild(frame);
  const doc = frame.contentDocument;
  const win = frame.contentWindow;
  if (!doc || !win) {
    frame.remove();
    return;
  }
  doc.open();
  doc.write(html);
  doc.close();
  const cleanup = () => setTimeout(() => frame.remove(), 1000);
  win.addEventListener("afterprint", cleanup);
  // Let images/styles settle before opening the dialog.
  setTimeout(() => {
    win.focus();
    win.print();
  }, 250);
}

export function printRows(title: string, rows: ExportRow[], meta?: string) {
  printHtml(htmlDocument(title, htmlTable(rows), meta));
}
